---
dist: bionic
addons:
  snaps:
    - hugo
script:
  - hugo
branches:
  only:
  - master
deploy:
  local_dir: public
  repo: samuelLawrence876/Hugo-toha-theme-deploy
  target_branch: master
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  email: $GITHUB_EMAIL
  name: $GITHUB_USERNAME
  on:
    branch: master
